config/routes.rb
Rails.application.routes.draw do
 
  
  
  
 
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'categories/:slug', to: 'sports#categories', as: :categories_sports


  root to: 'pages#index'
  
  get '/profil', to: 'users#edit', as: :profil

  patch '/profil', to: 'users#update'

 
 
  
  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :sport_categories
    resources :users
    resources :sports
    resources :posts
  end

  # Session à changer

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  #resources :sessions, only: [:new, :create, :destroy]

  resources :sports
  resources :posts do
    collection do
      get 'me'
    end
  end

  
  
  resources :users, only: [:new, :create, :show, :index, :destroy] do
    member do
      get 'confirm'
    end
   
    resource :follows, only: [:create, :destroy, :show]

    
    
  end

end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :user
  belongs_to :sport_categorie
  has_many :posts, dependent: :destroy
  
  validates :name, :date_begin, :frequence, presence: true
  validate :date_begin_not_future
  validates :photo_file, presence: true, on: :create

  has_image :photo
  def date_begin_not_future

    if date_begin.present? && date_begin.future?
      errors.add(:date_begin, 'ne peut être dans le futur')
    end
  
  end
end

app/controllers/admin/sports_controller.rb
module Admin
    class SportsController < ApplicationController

        before_action :set_sport, only: [ :destroy, :show]



        
        def index
            @sports = Sport.all
        end

        def show
            @sport = Sport.find(params[:id])
        end

        

        def destroy
            @sport.destroy

            redirect_to( admin_sports_path, success: "le post a été supprimé")

        end

        private
        def set_sport
            @sport = Sport.find(params[:id])

        end


    end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    before_action :set_sport, only: [:show, :edit, :update]
    skip_before_action :only_signed_in, only:[:show]

    def show
        @sport = Sport.find(params[:id])
    end

    def index
        @sports = current_user.sports
    end

    def new
        @sport = current_user.sports.new
    end
    
    def create
        @sport = current_user.sports.new(sport_params)

        if @sport.save

            redirect_to sports_path, success: 'Vous avez ajouté votre nouveau sport !'
        else
            render :new
        end
    
    end

    def edit
    
    end

    def update
        if @sport.update(sport_params)
            redirect_to sports_path, success: 'Votre sport a bien été modifié'
        else
            render :edit
        end
    end

    def destroy
        

        @sport = Sport.find(params[:id])
        if @sport.present?
            @sport.destroy
        end
        redirect_to sports_path, success: 'Votre sport a bien été supprimé'

    end

    private
    def sport_params
        params.require(:sport).permit(:name, :date_begin, :frequence, :sport_categorie_id, :photo_file)
    
    end

    def set_sport
        
       @sport = current_user.sports.find(params[:id])

    end

     
    
end

app/views/sports/_form.html.erb
<%= form_for sport, class: 'form-horizontal' do |f| %>

        <% if @sport.errors.any? %>
            <div class="alert alert-danger">
                <ul>
                    <% @sport.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>



        <div class="form-group">
            <%= f.label :name, "Sport", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>

        
        <div class="form-group">
            <%= f.label :date_begin, "Debut", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
                <%= f.date_select :date_begin, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :frequence, "Fréquence par semaine", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
                <%= f.select :frequence,[0, 1, 2, 3, 4, 5, 6, 7], {}, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :sport_categorie_id, "Catégorie", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
                <%= f.select :sport_categorie_id, SportCategorie.pluck(:name, :id), {}, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :photo_file, "Couverture du sport", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
                <%= f.file_field :photo_file, class: 'form-control' %>
            </div>
        </div>


      

        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-primary">
                <%= sport.new_record? ? 'Créer' : 'Modifier' %>
                </button>
            </div>
        </div>



<% end %>

app/views/sports/edit.html.erb
<% content_for :content do %>
<div class="card">
    <div class="card-header">Modifier <%= @sport.name %></div>
        <div class=" card-body">
            <%= render 'form', sport: @sport%>
        </div>
    
</div>
<% end %>
<%= render template: 'layouts/profile' %>

app/views/sports/index.html.erb
<% content_for :content do %>
<h5> Gérer mes sports</h5>

<p class="text-right">
    <a href="<%= new_sport_path %>" class="btn btn-primary">Ajouter un nouveau sport</a>
</p>


        <% @sports.each do |sport|%>

      
        <div class="card mb-4">

            <h5 class="card-header"><%= sport.name %></h5>

            <div class="card-body">
            
            <%= image_tag sport.photo_url %>
            <br>
        <%= current_user.firstname %> pratique ce sport <%= sport.frequence %> fois
        par semaine depuis le <%= sport.date_begin %>.

        <div class="d-flex justify-content-center p-2">
            <%= link_to 'Voir', sport, class: 'btn btn-primary md-2'%>
            <% if canEdit(sport) %>
                <%= link_to 'Modifier', [:edit, sport], class: 'btn btn-primary ml-2 md-2'%>
                <%= link_to 'Supprimer', sport, class: 'btn btn-danger ml-2', data: {method: :delete, confirm: 'Voulez vous vraiment supprimer ce sport'} %>
            <% end %>
        </div>
    </div>
    </div>

                   
    
        <% end %>
 



<% end %>
<%= render template: 'layouts/profile'%>

app/views/sports/new.html.erb
<% content_for :content do %>
<div class="card">
    <div class="card-header">Je pratique un nouveau sport</div>
        <div class=" card-body">
            <%= render 'form', sport: @sport%>
        </div>
    
</div>
<% end %>
<%= render template: 'layouts/profile' %>

app/views/sports/show.html.erb
<% content_for :content do %>


<h3><%= @sport.name %><h3>

    <% @sport.posts.each do |post| %>
        <div class="card mb-3" >

            <h5 class="card-header "><%= post.name %></h5>

            <div class="card-body x-2 y-2">
                <%= image_tag post.photo_url(:thumb) %>
                <br>
               
                <%= post.content %>.

                <div class="d-flex justify-content-center p-2">
                    <%= link_to 'Voir', post, class: 'btn btn-primary md-2'%>
                    <% if canEdit(post) %>
                        <%= link_to 'Modifier', [:edit, post], class: 'btn btn-primary ml-2 md-2'%>
                        <%= link_to 'Supprimer', post, class: 'btn btn-danger ml-2', data: {method: :delete, confirm: 'Voulez vous vraiment supprimer ce post'} %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>


<% end %>
<%= render template: 'layouts/profile' %>