config/routes.rb
Rails.application.routes.draw do
 
  
  
  
 
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'categories/:slug', to: 'sports#categories', as: :categories_sports


  root to: 'pages#index'
  
  get '/profil', to: 'users#edit', as: :profil

  patch '/profil', to: 'users#update'

 
 
  
  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :sport_categories
    resources :users
    resources :sports
    resources :posts
  end

  # Session à changer

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  #resources :sessions, only: [:new, :create, :destroy]

  resources :sports
  resources :posts do
    collection do
      get 'me'
    end
  end

  
  
  resources :users, only: [:new, :create, :show, :index, :destroy] do
    member do
      get 'confirm'
    end
   
    resource :follows, only: [:create, :destroy, :show]

    
    
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoddict</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

    <% if is_user_signed_in %>
    
     <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class ="navbar navbar-inverse">
        <div class ="container">
          <div class ="navbar-header">
            <a href="<%= root_path %>" class="navbar-brand">Spoddict</a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
              <%= link_to 'Acceuil', root_path, class: "nav-link" %>
            </li>

            <li class="nav-item active">
            <a class="nav-link" href="/profil">
            </a>
            </li>
            <li class="nav-item active">
              <%= link_to 'Mon espace', me_posts_path, class: "nav-link" %>
            </li>

            
            <li class="nav-item active">
            <a class="nav-link" href="/destroy"></a>
            </li>
            <li class="nav-item active">
              <%= link_to "Se déconnecter", destroy_session_path, data: {method: :delete}, class: "nav-link" %>
            </li>
          </ul>
           
          
    <% else %>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class ="navbar navbar-inverse">
          <div class ="container">
            <div class ="navbar-header">
              <a href="<%= root_path %>" class="navbar-brand">Spoddict</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item"><a class="nav-link" href="<%= root_path %>">Acceuil</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= new_user_path %>">S'inscrire</a></li>
              <li class="nav-item"><a class ="nav-link" href="<%= new_session_path %>">Se connecter </a></li>
            </ul>
    <% end %>

        </div>
      </div>
    </nav>


    <div class="container">

      <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% end %>

      <% if flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <% end %>

      
  <%= yield %>
      
    </div>
    
    <body>
    

    <%= javascript_pack_tag 'application','data-turbolinks-eval': 'false', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

  <footer class="main-footer">
<div class="d-flex justify-content-center m-4">
  <div class="ml-3"><a title="Polytech" class="" href="https://www.polytech.umontpellier.fr" target="_blank" rel="noopener noreferrer" data-testid="social-link">Polytech Montpellier</a></div>
  <div class="ml-3"><a title="GitHub" class="" href="https://github.com/lugonthier/ProjetWeb2" target="_blank" rel="noopener noreferrer" data-testid="social-link">Github</a></div>
  <div class="ml-3"><a title="Gouv" class="" href="https://www.service-public.fr/particuliers/vosdroits/F32239" target="_blank" rel="noopener noreferrer" data-testid="social-link">Harcèlement</a></div>

  
</div>
</footer>
</html>

app/views/layouts/profile.html.erb
<div class="container mb-6 ml-4">
<div class="row">
    <div class="col-8">
    <%= yield(:content) %>
    </div>
    <% if is_user_signed_in%>
    <div class="col-4">
        <div class="list-group">
            <a href="<%= profil_path %>" class="list-group-item">Mon compte</a>
            <a href="<%= sports_path %>" class="list-group-item">Mes sports</a>
            <a href="<%= me_posts_path %>" class="list-group-item">Mes photos</a>
            <a href="<%= posts_path %>" class="list-group-item">Mes abonnements</a>
            <% if current_user.admin  %>
                <a href="<%= admin_users_path %>" class="list-group-item">Gestion des utilisateurs</a>
                <a href="<%= admin_sports_path %>" class="list-group-item">Gestion des sports</a>
                <a href="<%= admin_sport_categories_path %>" class="list-group-item">Gestion des catégories</a>
                <a href="<%= admin_posts_path %>" class="list-group-item">Gestion des posts</a>
            <% end %>
        </div>
    </div>
  





    <% else %>
    <div class="col-4">
        <div class="list-group">
            <a href="<%= root_path %>" class="list-group-item">Accueil</a>
            <a href="<%= new_user_path %>" class="list-group-item">M'inscrire</a>
        </div>
    </div>
    <% end %>
</div>
</div>